<div class="ui page grid" style="padding-top: 70px;">
    <div class="ui page grid">
        <div class="ui page grid">
<?php $this->yieldView(); ?>
        </div>
    </div>
</div>
<code id="javascript-holder">
    <!--
    <?php
        try {
            echo mini(file_get_contents(dirname(__FILE__) . "/js/" . $this->viewName . ".js"));
        } catch(Exception $error){

        }
    ?>
    -->
</code>