<?php
$teamPick = $this->teamPick;

?>
<div class="row">
    <div class="column">
        <div class="ui three steps">
            <div class="<?= ($teamPick) ? "completed" : "active" ?> step">
                <i class="user icon"></i>

                <div class="content">
                    <div class="title">User Account</div>
                    <div class="description">Create an account for yourself</div>
                </div>
            </div>
            <div class="<?= ($teamPick) ? "completed" : "disabled" ?> step">
                <i class="at icon"></i>

                <div class="content">
                    <div class="title">Confirm Email</div>
                    <div class="description">Verify your email address</div>
                </div>
            </div>
            <div class="<?= ($teamPick) ? "active" : "disabled" ?> step">
                <i class="users icon"></i>

                <div class="content">
                    <div class="title">Team Selection</div>
                    <div class="description">Be a part of a team</div>
                </div>
            </div>
        </div>
        <div class="ui hidden divider"></div>
        <div class="ui segment hidden verify-email-alert">
            <h3>Email Verification required to complete registration.</h3>
            <p>
                A verification email has been sent to your email address. Please click on the link provided in the email to complete your registration. Also please check your spam folder for the email.
            </p>
            <p>
                If you do not receive the email in 10 minutes, please press the resend button below.
            </p>
            <a class="ui button"><i class="icon mail outline"></i>Resend Email</a>
        </div>
        <?php if ($teamPick != true): ?>
            <form class="ui form segment step-1 " method="post">

                <h4 class="ui dividing header">Personal Information</h4>

                <div class="field" style="margin-bottom: 0">
                    <label>Name</label>

                    <div class="two fields">
                        <div class="field">
                            <input type="text" name="first-name" placeholder="First Name">
                        </div>
                        <div class="field">
                            <input type="text" name="last-name" placeholder="Last Name">
                        </div>
                    </div>
                </div>


                <div class="field" style="width: 25% !important;">
                    <label>Gender</label>

                    <div class="ui selection dropdown">
                        <input type="hidden" name="gender">

                        <div class="default text">Gender</div>
                        <i class="dropdown icon"></i>

                        <div class="menu">
                            <div class="item" data-value="male">Male</div>
                            <div class="item" data-value="female">Female</div>
                        </div>
                    </div>
                </div>
                <div class="two fields">
                    <div class="field">
                        <label>About Yourself</label>
                        <textarea rows="1" style="height: 30px;" name="about"></textarea>
                    </div>
                </div>

                <h4 class="ui dividing header">Account Info</h4>

                <div class="two fields">
                    <div class="required field">
                        <label>Username</label>

                        <div class="ui icon input">
                            <input type="text" name="username" placeholder="Username">
                            <i class="username-icon user icon"></i>
                        </div>
                    </div>
                    <div class="required field">
                        <label>Password</label>

                        <div class="ui icon input">
                            <input type="password" name="password">
                            <i class="lock icon"></i>
                        </div>
                    </div>
                </div>
                <div class="required field">
                    <label>Email</label>

                    <div class="ui icon input">
                        <input type="text" name="email" placeholder="Email ID">
                        <i class="at icon"></i>
                    </div>
                </div>
                <div class="inline field">
                    <div class="ui checkbox">
                        <input type="checkbox" name="agree-tos">
                        <label>I agree to the <a onclick="openTos()">Terms of Service</a>.</label>
                    </div>
                </div>
                <!--<div class="ui error message">
                    <div class="header">We noticed some issues</div>
                </div>-->
                <div class="ui hidden divider"></div>

                <div class="ui submit button">Proceed to next step <i class="angle right icon"></i></div>
            </form>
        <?php endif;
        if ($teamPick == true): ?>
            <form class="ui form segment" method="post">
                <h4 class="ui dividing header">Join an Existing Team</h4>

                <div class="two fields">
                    <div class="required field">
                        <label>Team ID</label>

                        <div class="ui icon input">
                            <input type="text" placeholder="Team ID">
                            <i class="certificate icon"></i>
                        </div>
                    </div>
                    <div class="required field">
                        <label>Team Authentication Token</label>

                        <div class="ui icon input">
                            <input type="password" placeholder="Authentication Token">
                            <i class="lock icon"></i>
                        </div>
                    </div>
                </div>
                <div class="ui submit button">Authenticate and Complete Registration <i class="angle right icon"></i>
                </div>

            </form>
            <div class="ui center aligned">
                <div class="ui horizontal divider">Or</div>
            </div>
            <form class="ui form segment" method="post">

                <h4 class="ui dividing header">Create a New Team</h4>

                <div class="field">
                    <label>Team Name</label>

                    <div class="two fields">
                        <div class="field">
                            <input type="text" name="team-name" placeholder="Team Name">
                        </div>
                    </div>
                </div>
                <div class="field" style="margin-bottom: 0">
                    <label>This team represents</label>

                    <div class="two fields">
                        <div class="field">
                            <div class="ui fluid search selection dropdown">
                                <input type="hidden" name="country">
                                <i class="dropdown icon"></i>

                                <div class="default text">Select Country</div>
                                <div class="menu">
                                    <?php include "../../assets/raw/country-select-items.dat"; ?>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>


                <!--<div class="ui error message">
                    <div class="header">We noticed some issues</div>
                </div>-->
                <div class="ui hidden divider"></div>
                <div class="ui submit button">Create Team and Complete Registration <i class="angle right icon"></i>
                </div>
            </form>
        <?php endif; ?>

    </div>
</div>
<div class="ui modal">
    <i class="close icon"></i>

    <div class="content">
        <h3>Terms and Conditions</h3>

        <div id="tos-content">
            <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Duis pulvinar turpis maximus, mattis felis
                lacinia, sodales metus. Aenean id finibus orci. Mauris efficitur enim fermentum nunc accumsan pretium.
                Nulla neque metus, eleifend nec tincidunt ac, vulputate in nisi. Nunc vestibulum lacus ut turpis
                commodo, et egestas urna congue. Proin porttitor augue eget leo maximus tempus non at tellus. Phasellus
                eu tristique tellus, nec consequat nulla. Interdum et malesuada fames ac ante ipsum primis in faucibus.

            </p>

            <p>Mauris placerat massa nec est commodo, sed pulvinar orci posuere. Aenean sit amet sapien et mauris
                scelerisque lobortis placerat quis neque. Quisque hendrerit nisi in nulla blandit elementum. Suspendisse
                a sapien viverra elit aliquet faucibus. Aliquam consequat ante quam, nec dictum ex interdum eget. Proin
                vitae posuere velit, ac pharetra lorem. Integer purus tortor, maximus consequat dui ac, rutrum
                ullamcorper libero. Duis malesuada fermentum odio, non interdum mi blandit et. Proin pretium felis sed
                odio pretium maximus.

            </p>

            <p>Quisque dapibus, ipsum quis feugiat aliquet, odio libero posuere metus, a laoreet diam risus vel sapien.
                Ut laoreet massa ut risus tincidunt sodales. Aliquam rutrum turpis et dignissim dictum. Nam vitae enim
                nunc. Maecenas lacus dolor, malesuada non nibh id, cursus pulvinar arcu. Curabitur ac consequat tellus.
                In mattis vel elit vitae tempus. Pellentesque in orci sed nisi fringilla faucibus a sit amet diam. Nulla
                nec posuere nibh.

            </p>

            <p>Praesent turpis neque, sollicitudin eget nisi id, interdum mollis neque. Aenean tincidunt a lacus ac
                pretium. Donec nisi purus, porttitor et tincidunt in, iaculis sit amet nibh. Etiam pretium egestas
                rutrum. Quisque ex nisl, finibus eu ex sed, feugiat pulvinar felis. Sed eget mi sit amet massa iaculis
                porta. Integer porta ligula at ante viverra finibus quis aliquam odio. Pellentesque risus dolor,
                dignissim et diam convallis, tempus egestas orci. Nullam ornare fermentum aliquam.

            </p>

            <p>Fusce mauris felis, varius id vulputate ut, hendrerit ut nibh. Donec mollis, enim nec consectetur
                vestibulum, risus purus aliquam turpis, a vestibulum libero diam ac lacus. Maecenas a lectus at odio
                viverra consequat ut nec sapien. Donec ut leo interdum nibh ultrices lobortis et ac mi. Praesent
                consequat, nunc nec finibus finibus, orci erat auctor sapien, a facilisis nulla neque eu mi. Sed
                placerat orci eu nibh sollicitudin, eget dictum erat sollicitudin. Donec et faucibus ante. Nam ex massa,
                feugiat eu enim ut, pellentesque lobortis turpis. Vestibulum ut maximus elit, at fermentum est. Nunc
                commodo ligula vel dui sodales ultricies. Sed consequat, diam vel accumsan euismod, nibh ipsum semper
                nisi, a efficitur ex ex vel lectus. Phasellus consectetur sed mi ac pellentesque. Nam nec tincidunt leo,
                in pellentesque ante. Donec egestas lobortis arcu imperdiet malesuada. Aliquam eget justo ligula.
                Praesent nec elit sit amet nisi aliquet maximus id vel odio.

            </p>
        </div>
    </div>
</div>
